name: Tests
on: [push]

jobs:
  Composer:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist --no-dev
  PHPunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} unit tests on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: gd, sqlite3
      
    # composer cache
    - name: Remove composer lock
      run: rm composer.lock
    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    # http://man7.org/linux/man-pages/man1/date.1.html
    # https://github.com/actions/cache#creating-a-cache-key
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-${{ steps.get-date.outputs.date }}-
    
    # composer
    - name: Setup PHPunit
      run: composer install -n
    - name: Install Google Cloud Storage
      run: composer require google/cloud-storage
    
    # testing
    - name: Run unit tests
      run: ../vendor/bin/phpunit --no-coverage
      working-directory: tst
  Mocha:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Setup Mocha
      run: npm install -g mocha
    - name: Setup Node modules
      run: npm install
      working-directory: js
    - name: Run unit tests
      run: mocha
      working-directory: js

